# Generated by Django 5.2.3 on 2025-09-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("supplierManagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Analgesic", "Analgesic"),
                            ("Antibiotic", "Antibiotic"),
                            ("Antiviral", "Antiviral"),
                            ("Antifungal", "Antifungal"),
                            ("Antihistamine", "Antihistamine"),
                            ("Antacid", "Antacid"),
                            ("Antipyretic", "Antipyretic"),
                            ("Anti-inflammatory", "Anti-inflammatory"),
                            ("Antihypertensive", "Antihypertensive"),
                            ("Antidiabetic", "Antidiabetic"),
                            ("Antidepressant", "Antidepressant"),
                            ("Anticoagulant", "Anticoagulant"),
                            ("Diuretic", "Diuretic"),
                            ("Sedative", "Sedative"),
                            ("Bronchodilator", "Bronchodilator"),
                            ("Vaccine", "Vaccine"),
                            ("Steroid", "Steroid"),
                            ("Contraceptive", "Contraceptive"),
                            ("Antiemetic", "Antiemetic"),
                            ("Antipsychotic", "Antipsychotic"),
                            ("Muscle Relaxant", "Muscle Relaxant"),
                            ("Chemotherapy", "Chemotherapy"),
                            ("Immunosuppressant", "Immunosuppressant"),
                            ("Ophthalmic", "Ophthalmic"),
                            ("Dermatological", "Dermatological"),
                            ("Nutritional Supplement", "Nutritional Supplement"),
                            ("Respiratory Agent", "Respiratory Agent"),
                            ("Local Anesthetic", "Local Anesthetic"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "medicine_type",
                    models.CharField(
                        choices=[("RX", "RX"), ("OTC", "OTC")],
                        default="RX",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("dosage", models.CharField(max_length=50)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="medical_products/"
                    ),
                ),
                ("quantity_in_stock", models.PositiveIntegerField()),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                ("manufacture_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("batch_number", models.CharField(max_length=150, unique=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medicines",
                        to="supplierManagement.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Medicine_inventory.medicine",
                    ),
                ),
            ],
        ),
    ]
