# Generated by Django 5.2.3 on 2025-07-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                choices=[
                    ("Tablet", "Tablet"),
                    ("Syrup", "Syrup"),
                    ("Injection", "Injection"),
                    ("Capsule", "Capsule"),
                    ("Ointment", "Ointment"),
                ],
                max_length=50,
            ),
        ),
    ]
