# Generated by Django 5.2.3 on 2025-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineaction",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
