# Generated by Django 5.2.3 on 2025-09-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0003_medicineaction_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="available_online",
            field=models.BooleanField(
                default=False,
                help_text="Make this medicine available for online purchase",
            ),
        ),
    ]
