# Generated by Django 5.2.3 on 2025-09-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0003_medicineaction_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
