# Generated by Django 5.2.3 on 2025-07-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0004_medicineaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="medicineaction",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Medicine_inventory.medicine",
            ),
        ),
    ]
