# Generated by Django 5.2.3 on 2025-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0005_alter_medicineaction_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineaction",
            name="batch_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicineaction",
            name="medicine_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
