# Generated by Django 5.2.3 on 2025-08-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0010_medicine_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="medical_products/"
            ),
        ),
    ]
