# Generated by Django 5.2.3 on 2025-09-01 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customer_city_customer_country_customer_nic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_hired",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
