# Generated by Django 5.2.3 on 2025-10-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(default="0700000000", max_length=10),
        ),
    ]
