# Generated by Django 5.2.3 on 2025-10-14 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_customer_nic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="nic",
            field=models.CharField(
                default="000000000V",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?:\\d{9}[VvXx]|\\d{12})$",
                        message="Enter a valid Sri Lankan NIC (old: 9 digits + V/v/X, or new: 12 digits).",
                    )
                ],
                verbose_name="NIC Number",
            ),
        ),
    ]
