# Generated by Django 5.2.3 on 2025-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sage",
            field=models.IntegerField(default=0),
        ),
    ]
