# Generated by Django 5.2.3 on 2025-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudApp", "0002_student_sage"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sdob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
