# Generated by Django 5.2.3 on 2025-09-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Tablet", "Tablet"),
                            ("Capsule", "Capsule"),
                            ("Syrup", "Syrup"),
                            ("Injection", "Injection"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Supplier Name"),
                ),
                ("contact_person", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                (
                    "supplier_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Manufacturer", "Manufacturer"),
                            ("Distributor", "Distributor"),
                            ("Wholesaler", "Wholesaler"),
                            ("Local Vendor", "Local Vendor"),
                            ("International Vendor", "International Vendor"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "products_supplied",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Medicines", "Medicines"),
                            ("OTC", "OTC"),
                            ("Medical Devices", "Medical Devices"),
                            ("Non-medical", "Non-medical"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=100)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Tax/Registration Number",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, help_text="e.g. Net 30, Net 60, COD", max_length=50
                    ),
                ),
                (
                    "bank_details",
                    models.TextField(
                        blank=True, help_text="Optional, for direct payments"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Blacklisted", "Blacklisted"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suppliers",
                        to="supplierManagement.product",
                    ),
                ),
            ],
        ),
    ]
