# Generated by Django 5.2.3 on 2025-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Analgesic", "Analgesic"),
                            ("Antibiotic", "Antibiotic"),
                            ("Antiviral", "Antiviral"),
                            ("Antifungal", "Antifungal"),
                            ("Antihistamine", "Antihistamine"),
                            ("Antacid", "Antacid"),
                            ("Antipyretic", "Antipyretic"),
                            ("Anti-inflammatory", "Anti-inflammatory"),
                            ("Antihypertensive", "Antihypertensive"),
                            ("Antidiabetic", "Antidiabetic"),
                            ("Antidepressant", "Antidepressant"),
                            ("Anticoagulant", "Anticoagulant"),
                            ("Diuretic", "Diuretic"),
                            ("Sedative", "Sedative"),
                            ("Bronchodilator", "Bronchodilator"),
                            ("Vaccine", "Vaccine"),
                            ("Steroid", "Steroid"),
                            ("Contraceptive", "Contraceptive"),
                            ("Antiemetic", "Antiemetic"),
                            ("Antipsychotic", "Antipsychotic"),
                            ("Muscle Relaxant", "Muscle Relaxant"),
                            ("Chemotherapy", "Chemotherapy"),
                            ("Immunosuppressant", "Immunosuppressant"),
                            ("Ophthalmic", "Ophthalmic"),
                            ("Dermatological", "Dermatological"),
                            ("Nutritional Supplement", "Nutritional Supplement"),
                            ("Respiratory Agent", "Respiratory Agent"),
                            ("Local Anesthetic", "Local Anesthetic"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("contact_person", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suppliers",
                        to="supplierManagement.product",
                    ),
                ),
            ],
        ),
    ]
