# Generated by Django 5.2.3 on 2025-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplierManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Tablet", "Tablet"),
                    ("Capsule", "Capsule"),
                    ("Syrup", "Syrup"),
                    ("Injection", "Injection"),
                ],
                max_length=50,
            ),
        ),
    ]
