# Generated by Django 5.2.3 on 2025-10-13 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplierManagement", "0002_alter_product_category_purchaseorder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="product_name",
            field=models.CharField(default="Unknown Product", max_length=150),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="Medicines", max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="expected_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Ordered", "Ordered"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="supplierManagement.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_items",
                to="supplierManagement.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="payment_terms",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="products_supplied",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Medicines", "Medicines"),
                    ("OTC", "OTC"),
                    ("Medical Devices", "Medical Devices"),
                    ("Non-medical", "Non-medical"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Manufacturer", "Manufacturer"),
                    ("Distributor", "Distributor"),
                    ("Wholesaler", "Wholesaler"),
                    ("Local Vendor", "Local Vendor"),
                    ("International Vendor", "International Vendor"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="tax_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
