# Generated by Django 5.2.3 on 2025-08-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NonMedicalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cosmetics", "Cosmetics"),
                            ("personal_care", "Personal Care"),
                            ("baby_products", "Baby Products"),
                            ("supplements", "Supplements"),
                            ("medical_devices", "Medical Devices"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="non_medical_products/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reorder_level", models.PositiveIntegerField(default=5)),
            ],
            options={
                "verbose_name": "Non-Medical Product",
                "verbose_name_plural": "Non-Medical Products",
                "ordering": ["name"],
            },
        ),
    ]
