# Generated by Django 5.2.3 on 2025-08-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Non_Medicine_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonmedicalproduct",
            name="brand",
            field=models.CharField(default="No_Brand", max_length=255),
        ),
    ]
