# Generated by Django 5.2.4 on 2025-08-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Non_Medicine_inventory", "0002_nonmedicalproduct_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonmedicalproduct",
            name="brand",
            field=models.CharField(max_length=255),
        ),
    ]
