# Generated by Django 5.2.3 on 2025-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Non_Medicine_inventory", "0002_auto_20250923_0954"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonmedicalproduct",
            name="available_online",
            field=models.BooleanField(default=True),
        ),
    ]
