# Generated by Django 5.2.3 on 2025-08-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Non_Medicine_inventory", "0003_alter_nonmedicalproduct_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonmedicalproduct",
            name="category",
            field=models.CharField(
                choices=[
                    ("Cosmetics", "Cosmetics"),
                    ("Personal care", "Personal Care"),
                    ("Baby Products", "Baby Products"),
                    ("Supplements", "Supplements"),
                    ("Medical Devices", "Medical Devices"),
                    ("Other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
