# Generated by Django 5.2.3 on 2025-09-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Non_Medicine_inventory", "0003_nonmedicalproduct_available_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonmedicalproduct",
            name="available_online",
            field=models.BooleanField(
                default=True, help_text="Is this product available online?"
            ),
        ),
    ]
