# Generated by Django 5.2.3 on 2025-09-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Non_Medicine_inventory", "0004_alter_nonmedicalproduct_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonmedicalproduct",
            name="available_online",
            field=models.BooleanField(default=True),
        ),
    ]
