# Generated by Django 5.2.4 on 2025-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="medical_code",
            field=models.CharField(
                default=0,
                help_text="Unique medical license or registration code",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
