# Generated by Django 5.2.4 on 2025-08-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_doctor_medical_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
