# Generated by Django 5.2.4 on 2025-08-31 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine_inventory', '0012_medicineaction_user'),
        ('Non_Medicine_inventory', '0004_alter_nonmedicalproduct_category'),
        ('onlineStore', '0002_remove_order_cart_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('medicine', 'Medicine'), ('non_medical', 'Non-Medical Product')], max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('available_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_product', to='Medicine_inventory.medicine')),
                ('non_medical_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_product', to='Non_Medicine_inventory.nonmedicalproduct')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
