# Generated by Django 5.2.4 on 2025-09-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0002_order_shipping_address_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
