# Generated by Django 5.2.4 on 2025-09-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0003_remove_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment_Failed', 'Payment Failed'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
