# Generated by Django 5.2.4 on 2025-09-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0004_alter_product_options_alter_product_medicine_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
