# Generated by Django 5.2.3 on 2025-09-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlineStore", "0005_order_shipping_address_order_shipping_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Payment Failed", "Payment Failed"),
                    ("Paid", "Paid"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
