# Generated by Django 5.2.3 on 2025-10-13 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlinePrescription", "0002_alter_prescription_nic_alter_prescription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="nic",
            field=models.CharField(
                help_text="Enter 9-digit + V/v/X (old) or 12-digit (new) NIC",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?:\\d{9}[VvXx]|\\d{12})$",
                        message="Enter a valid Sri Lankan NIC (old: 9 digits + V/v/X, or new: 12 digits).",
                    )
                ],
            ),
        ),
    ]
