# Generated by Django 5.2.3 on 2025-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("dosage", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_in_stock", models.PositiveIntegerField()),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                ("manufacture_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("supplier", models.CharField(max_length=100)),
            ],
        ),
    ]
