# Generated by Django 5.2.3 on 2025-07-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0002_alter_medicine_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="batch_number",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                choices=[
                    ("Analgesic", "Analgesic"),
                    ("Antibiotic", "Antibiotic"),
                    ("Antiviral", "Antiviral"),
                    ("Antifungal", "Antifungal"),
                    ("Antihistamine", "Antihistamine"),
                    ("Antacid", "Antacid"),
                    ("Antipyretic", "Antipyretic"),
                    ("Anti-inflammatory", "Anti-inflammatory"),
                    ("Antihypertensive", "Antihypertensive"),
                    ("Antidiabetic", "Antidiabetic"),
                    ("Antidepressant", "Antidepressant"),
                    ("Anticoagulant", "Anticoagulant"),
                    ("Diuretic", "Diuretic"),
                    ("Sedative", "Sedative"),
                    ("Bronchodilator", "Bronchodilator"),
                    ("Vaccine", "Vaccine"),
                    ("Steroid", "Steroid"),
                    ("Contraceptive", "Contraceptive"),
                    ("Antiemetic", "Antiemetic"),
                    ("Antipsychotic", "Antipsychotic"),
                    ("Muscle Relaxant", "Muscle Relaxant"),
                    ("Chemotherapy", "Chemotherapy"),
                    ("Immunosuppressant", "Immunosuppressant"),
                    ("Ophthalmic", "Ophthalmic"),
                    ("Dermatological", "Dermatological"),
                    ("Nutritional Supplement", "Nutritional Supplement"),
                    ("Respiratory Agent", "Respiratory Agent"),
                    ("Local Anesthetic", "Local Anesthetic"),
                ],
                max_length=50,
            ),
        ),
    ]
