# Generated by Django 5.2.3 on 2025-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0006_medicineaction_batch_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="medicine_type",
            field=models.CharField(
                choices=[("RX", "Rx Medicine"), ("OTC", "Over the Counter medicine")],
                default="RX",
                max_length=3,
            ),
        ),
    ]
