# Generated by Django 5.2.3 on 2025-08-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0007_medicine_medicine_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="price",
        ),
        migrations.AddField(
            model_name="medicine",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="medicine",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="medicine_type",
            field=models.CharField(
                choices=[("RX", "RX"), ("OTC", "OTC")], default="RX", max_length=3
            ),
        ),
    ]
