# Generated by Django 5.2.3 on 2025-08-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Medicine_inventory",
            "0008_remove_medicine_price_medicine_cost_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="medicine_type",
            field=models.CharField(
                choices=[("RX", "RX"), ("OTC", "OTC")], default="RX", max_length=10
            ),
        ),
    ]
