# Generated by Django 5.2.3 on 2025-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0009_alter_medicine_medicine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="non_medical_products/"
            ),
        ),
    ]
