# Generated by Django 5.2.3 on 2025-09-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0012_medicineaction_user"),
        ("supplierManagement", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="supplierManagement.supplier",
            ),
        ),
    ]
