# Generated by Django 5.2.3 on 2025-09-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0013_alter_medicine_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicineaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Updated", "Updated"),
                    ("Deleted", "Deleted"),
                ],
                max_length=10,
            ),
        ),
    ]
