# Generated by Django 5.2.3 on 2025-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Medicine_inventory", "0015_medicine_med_code_alter_medicine_batch_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="med_code",
        ),
        migrations.AlterField(
            model_name="medicine",
            name="batch_number",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
